version: '3'
services:
  phx:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - MIX_ENV=test
    volumes:
      - '.:/app'
    ports:
      - '4008:4008'
    command: tail -F /dev/null
