services:
  phx:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - MIX_ENV=test
    volumes:
      - '.:/app'
      # These lines ensure the deps can be saved as build artifacts for caching
      - '/app/deps'
      - '/app/_build'
    ports:
      - '4008:4008'
    command: tail -F /dev/null
